#!/bin/bash
PORT=${PORT-8000}
curl \
	-D - \
	-X $1 -d "$2" \
	--header "Content-Type: ${CONTENT_TYPE:-application/json}" \
	--header "Accept: ${ACCEPT:-application/json}" \
	--header "Authorization: $API_KEY" \
	--header "Revision-Userdata: $USERDATA" \
	--header "Base-Revision-Id: $BASEREV" \
	http://localhost:$PORT/api/v1$3
