#!/bin/bash

rm -rf /tmp/swagger-ui
git clone https://github.com/swagger-api/swagger-ui /tmp/swagger-ui
mv /tmp/swagger-ui/dist frontend/public_html/apidocs
rm -rf /tmp/swagger-ui
cp backend/swagger.html frontend/public_html/apidocs/index.html
cp backend/swagger.yaml frontend/public_html/apidocs/swagger.yaml
